from __future__ import annotations

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from PySide6.QtWidgets import QMainWindow

    class DashboardMixinBase(QMainWindow):
        """Static-analysis base for dashboard mixins.

        The real SecureAccessDashboard combines many mixins with QMainWindow.
        Pylance analyses each mixin alone, so this base tells the type checker
        that ``self`` has QMainWindow methods and dynamic dashboard attributes.
        Runtime inheritance remains plain object.
        """

        _allow_settings_disconnect_popup_once: Any
        _append_text_audit_row: Any
        _audit_append_system_log: Any
        _audit_detail_label: Any
        _audit_detail_pairs: Any
        _audit_detail_value: Any
        _audit_plain_text: Any
        _audit_read_credentials: Any
        _audit_text_safe: Any
        _auto_minimize_enabled: Any
        _browse_zip_file_into: Any
        _camera_preview_running: Any
        _camera_resume_after_modal: Any
        _camera_rotation_poll_in_progress: Any
        _camera_rotation_sync_in_progress: Any
        _camera_user_stopped: Any
        _card_dialog_dim_overlays: Any
        _card_dialog_open_count: Any
        _circle_flip_animating: Any
        _clean_pi_sftp_host: Any
        _closing: Any
        _connect_smb_share_if_needed: Any
        _connection_blur_anim: Any
        _countdown_flip_anim_1: Any
        _countdown_flip_anim_2: Any
        _create_transfer_tabs: Any
        _do_logout: Any
        _download_dataset_sftp_to_windows: Any
        _face_api_base_url: Any
        _face_api_capture_user: Any
        _face_api_check_received: Any
        _face_api_delete_user: Any
        _face_api_export_data: Any
        _face_api_get_result: Any
        _face_api_import_data: Any
        _face_api_load_logs: Any
        _face_api_refresh_users: Any
        _face_api_request: Any
        _face_api_sftp_send: Any
        _face_api_stop_recognition: Any
        _face_api_sync_settings_to_pi: Any
        _face_api_test_connection: Any
        _face_api_train: Any
        _force_clear_card_dialog_background: Any
        _format_audit_details: Any
        _get_backend_pi_sftp_config: Any
        _grant_access: Any
        _guidelines_dialog: Any
        _handle_sas_received_pending: Any
        _handling_pi_disconnect: Any
        _idle_event_filter_installed: Any
        _keep_session_credentials_visible: Any
        _last_user_activity_ts: Any
        _last_websocket_result_state: Any
        _load_admins: Any
        _locked_input_options_summary: Any
        _log_update_pending: Any
        _login_popup_active: Any
        _manual_connect_failed_popup_active: Any
        _minimized_by_sas: Any
        _missing_credentials_popup_shown: Any
        _modal_open_count: Any
        _multi_sftp_add_target: Any
        _multi_sftp_apply_poll_interval: Any
        _multi_sftp_apply_snapshot: Any
        _multi_sftp_build_progress_row: Any
        _multi_sftp_cancel_batch: Any
        _multi_sftp_cleanup_and_close: Any
        _multi_sftp_filtered_targets: Any
        _multi_sftp_load_targets: Any
        _multi_sftp_minimize_progress: Any
        _multi_sftp_open_progress_window: Any
        _multi_sftp_poll_batch: Any
        _multi_sftp_poll_interval_ms: Any
        _multi_sftp_position_progress_window: Any
        _multi_sftp_progress_action: Any
        _multi_sftp_progress_dialog: Any
        _multi_sftp_refresh_target_rows: Any
        _multi_sftp_remove_target: Any
        _multi_sftp_render_progress: Any
        _multi_sftp_render_setup: Any
        _multi_sftp_request_close: Any
        _multi_sftp_restore_progress_window: Any
        _multi_sftp_retry_failed: Any
        _multi_sftp_set_status: Any
        _multi_sftp_start_batch: Any
        _multi_sftp_start_polling: Any
        _multi_sftp_update_select_all: Any
        _multi_sftp_update_transfer_button: Any
        _normalise_audit_detail_key: Any
        _normalise_received_pending_items: Any
        _normalized_settings_snapshot_for_compare: Any
        _open_face_user_expand_card: Any
        _parse_legacy_audit_message: Any
        _parse_websocket_timestamp: Any
        _pending_auto_lock: Any
        _pending_face_detected_state: Any
        _pi_connect_request_token: Any
        _pi_disconnect_deferred_during_login: Any
        _pi_disconnect_deferred_origin: Any
        _pi_disconnect_deferred_reason: Any
        _pi_disconnect_last_auto_popup_ts: Any
        _pi_disconnect_lock_suspended: Any
        _pi_disconnect_popup_last_shown_at: Any
        _pi_disconnect_popup_user_closed: Any
        _pi_disconnect_popup_visible: Any
        _pi_disconnect_reason: Any
        _pi_disconnect_retry_active: Any
        _pi_disconnect_retry_running: Any
        _pi_host_dirty_since_edit: Any
        _pi_host_user_editing: Any
        _pi_selected_host_pending_manual_connect: Any
        _pi_storage_last_snapshot: Any
        _pi_storage_poll_in_progress: Any
        _poll_received_face_data_for_sas: Any
        _position_sas_received_badge: Any
        _read_credentials: Any
        _received_item_display_text: Any
        _remove_admin: Any
        _resolve_connected_pi_sftp_user: Any
        _sas_log_lock: Any
        _sas_server_log_last_error: Any
        _sas_server_log_last_warn_at: Any
        _sas_server_log_lock: Any
        _sas_server_log_skip_until: Any
        _sas_server_log_write_running: Any
        _sas_received_badge_count: Any
        _save_admin: Any
        _save_credentials: Any
        _session_settings_ntid: Any
        _session_settings_password: Any
        _session_settings_server: Any
        _settings_bypass_unsaved_prompt_once: Any
        _settings_close_after_save: Any
        _settings_connect_attempt_id: Any
        _settings_connect_in_progress: Any
        _settings_dirty_since_baseline: Any
        _settings_discard_restore_in_progress: Any
        _settings_programmatic_update: Any
        _settings_save_prompt_active: Any
        _settings_unsaved_baseline: Any
        _settings_validation_passed: Any
        _show_card_dialog: Any
        _show_sas_desktop_notification: Any
        _show_sas_received_popup: Any
        _startup_background_check_done: Any
        _startup_background_check_pending: Any
        _startup_disconnect_popup_shown: Any
        _startup_minimize_done: Any
        _suppress_lock_notification: Any
        _system_log_lines: Any
        _training_waiting_for_capture_stop: Any
        _transfer_blur_anim: Any
        _transfer_dim_overlay: Any
        _unc_share_root: Any
        _update_sas_received_badge: Any
        _validate_ntid_in_ad: Any
        _validate_ntid_password_in_ad: Any
        _validate_windows_download_inputs: Any
        _websocket_seen_events: Any
        account_menu: Any
        activateWindow: Any
        active_transfer_dialog: Any
        ad_service: Any
        add_admin_from_ui: Any
        add_path_browse_button: Any
        adjust_footer_width: Any
        admin_add_input: Any
        admin_list_layout: Any
        admin_list_scroll: Any
        admin_management_card: Any
        admin_row: Any
        admin_service: Any
        animate_tab_indicator: Any
        append_face_log: Any
        append_system_log: Any
        apply_app_icon: Any
        apply_lock_state: Any
        apply_security_options_runtime: Any
        apply_session_credentials_to_settings_ui: Any
        apply_styles: Any
        apply_timeout_to_countdown: Any
        apply_window_chrome: Any
        auto_capture_card: Any
        auto_capture_enabled: Any
        auto_capture_toggle: Any
        auto_connect_pi_for_face_tab: Any
        browse_server_path: Any
        build_account_menu: Any
        build_dashboard_page: Any
        build_face_circle_back: Any
        build_face_page: Any
        build_footer_area: Any
        build_footer_strip: Any
        build_header: Any
        build_login_page: Any
        build_settings_page: Any
        build_time_section: Any
        build_timer_circle_front: Any
        build_ui: Any
        build_unified_dashboard_card: Any
        build_window: Any
        camera_capture: Any
        camera_feed_card: Any
        camera_feed_url: Any
        camera_fps: Any
        camera_frame_count: Any
        camera_last_tick: Any
        camera_preview_label: Any
        camera_rotation: Any
        camera_rotation_buttons: Any
        camera_rotation_card: Any
        camera_rotation_label: Any
        camera_rotation_poll_timer: Any
        camera_rotation_status_label: Any
        camera_state_badge: Any
        camera_timer: Any
        can_show_pi_disconnect_popup_now: Any
        card_padding: Any
        centralWidget: Any
        check_pi_camera_status_and_update_panel: Any
        circle_flip_container: Any
        circle_flip_overlay: Any
        circle_stack: Any
        claim_pi_oneconnect_session: Any
        clear_all_authorized_users_ui: Any
        clear_blur_effect: Any
        clear_disconnect_popup_overlay: Any
        clear_layout_widgets: Any
        clear_ntid_input_error: Any
        clear_sensitive_server_credentials_ui: Any
        clear_session_credentials_on_logout: Any
        clear_transfer_text_selection: Any
        clock_timer: Any
        close: Any
        close_after_settings_save: Any
        close_connection_dialog_silently: Any
        cleanup_expired_sas_logs: Any
        close_guidelines_dialog_if_open: Any
        compact_mode: Any
        configure_recognition_websocket: Any
        connection_dialog: Any
        consume_deferred_pi_disconnect_reason: Any
        content_max_width: Any
        convert_connection_dialog_to_disconnect_failed: Any
        count_timer: Any
        countdown_card: Any
        countdown_card_widget: Any
        countdown_label: Any
        countdown_title_label: Any
        create_multi_sftp_progress_dialog: Any
        create_multi_sftp_transfer_dialog: Any
        create_sftp_windows_transfer_dialog: Any
        create_timeout_input: Any
        create_transfer_dialog_base: Any
        credential_service: Any
        current_top_tab: Any
        current_user: Any
        current_user_role: Any
        dashboard_authorized_users_btn: Any
        dashboard_cards: Any
        dashboard_page: Any
        dashboard_protocol_label: Any
        dashboard_users_box: Any
        dashboard_users_status: Any
        date_label: Any
        defer_pi_disconnect_until_after_login: Any
        destroyed: Any
        disable_keyboard_when_locked: Any
        disable_mouse_when_locked: Any
        disable_usb_when_locked: Any
        discard_unsaved_settings_changes: Any
        disconnect_pi_from_settings: Any
        disconnect_pi_oneconnect_session: Any
        emergency_recovery_timer: Any
        enable_hotkey: Any
        end_websocket_lock_session: Any
        ensure_pi_recognition_after_training: Any
        ensure_taskbar_window_identity: Any
        enter_first_launch_setup_mode: Any
        exit_first_launch_setup_mode: Any
        face_action_feedback: Any
        face_api_service: Any
        face_capture_btn: Any
        face_capture_in_progress: Any
        face_cards: Any
        face_circle_back: Any
        face_controls_card: Any
        face_data_transfer_card: Any
        face_delete_btn: Any
        face_detected: Any
        face_detected_circle_text: Any
        face_detected_icon: Any
        face_name_input: Any
        face_page: Any
        face_recognize_btn: Any
        face_state_label: Any
        face_stop_btn: Any
        face_train_btn: Any
        face_user_row: Any
        face_user_search_input: Any
        face_users_body: Any
        face_users_cache: Any
        face_users_card: Any
        face_users_layout: Any
        face_users_list_layout: Any
        face_users_scroll: Any
        face_users_subtitle: Any
        findChildren: Any
        finish_auto_lock_after_ring: Any
        finish_connection_dialog_failed: Any
        finish_connection_dialog_success: Any
        finish_export_progress_then_success: Any
        finish_import_progress_then_success: Any
        finish_pi_disconnect_retry_cycle: Any
        first_launch_setup_mode: Any
        flip_countdown_circle: Any
        flush_face_log_label: Any
        footer_area: Any
        footer_line_1: Any
        footer_line_2: Any
        footer_server_label: Any
        footer_state_label: Any
        footer_strip: Any
        footer_timeout_label: Any
        format_lock_interval: Any
        format_storage_bytes: Any
        frameGeometry: Any
        geometry: Any
        get_audit_actor: Any
        get_effective_idle_seconds: Any
        get_pi_host_for_connection_origin: Any
        get_sas_client_display_name: Any
        get_saved_server_credentials: Any
        get_saved_settings_snapshot_for_save_prompt: Any
        get_settings_ui_snapshot_for_save_prompt: Any
        get_user_capture_frames_from_pi: Any
        get_windows_system_idle_seconds: Any
        grab_circle_face: Any
        guidelines_help_btn: Any
        handle_camera_feed_unavailable: Any
        handle_login_button_clicked: Any
        handle_minimized_disconnect_state: Any
        handle_missing_pi_host_disconnect_state: Any
        handle_oneconnect_connection_lost: Any
        handle_pi_host_text_edited: Any
        handle_pi_runtime_disconnect: Any
        handle_startup_background_check_result: Any
        handle_websocket_connected: Any
        handle_websocket_disconnected: Any
        handle_websocket_recognition_message: Any
        has_restricted_tab_access: Any
        has_unsaved_settings_changes: Any
        height: Any
        hide_system_locked_notification: Any
        install_idle_activity_tracker: Any
        isMaximized: Any
        isMinimized: Any
        isVisible: Any
        is_admin: Any
        is_locked: Any
        is_logged_in: Any
        is_login_popup_active: Any
        is_manual_settings_connect_in_progress: Any
        is_pi_host_editing_blocking_auto_connect: Any
        is_sas_minimized_or_background: Any
        is_server_configured: Any
        is_settings_tab_active: Any
        keep_pi_disconnected_warning_active: Any
        load_or_create_sas_client_id: Any
        load_settings_from_credentials: Any
        lock_timeout_seconds: Any
        login_btn: Any
        login_debug: Any
        login_ntid_input: Any
        login_page: Any
        login_password_input: Any
        login_requested: Any
        login_status_label: Any
        login_toggle_btn: Any
        make_scrollbar_invisible: Any
        manual_capture_active: Any
        manual_capture_user: Any
        manual_lock_btn: Any
        mark_settings_modified_by_user: Any
        mark_user_activity: Any
        maybe_prompt_unsaved_settings_before_leave: Any
        minimize_after_face_unlock: Any
        minimize_once_after_startup: Any
        minimize_to_taskbar_for_lock: Any
        minimize_to_taskbar_if_safe: Any
        move: Any
        nav_header: Any
        normalize_camera_rotation: Any
        normalize_sftp_pending_path: Any
        normalize_timeout_input: Any
        ntid_input: Any
        on_auto_capture_toggle_changed: Any
        oneconnect_payload: Any
        open_authorized_users_popup: Any
        open_login_popup: Any
        pause_camera_for_modal: Any
        pending_restricted_tab: Any
        pi_api_base: Any
        pi_api_host: Any
        pi_api_port: Any
        pi_connect_btn: Any
        pi_connected: Any
        pi_connection_checked: Any
        pi_connectivity_card: Any
        pi_device_hostname: Any
        pi_host_input: Any
        pi_identity_label: Any
        pi_status_label: Any
        pi_storage_card: Any
        pi_storage_detail_label: Any
        pi_storage_poll_timer: Any
        pi_storage_progress: Any
        pi_storage_refresh_button: Any
        pi_storage_status_label: Any
        pi_storage_summary_label: Any
        pi_system_user: Any
        poll_camera_rotation_from_pi: Any
        position_account_menu: Any
        pull_pi_settings_to_sas: Any
        qt_after: Any
        raise_: Any
        rebuild_export_failed_card: Any
        rebuild_export_loading_card: Any
        rebuild_export_success_card: Any
        rebuild_import_failed_card: Any
        rebuild_import_loading_card: Any
        rebuild_import_success_card: Any
        rect: Any
        refresh_admin_list_ui: Any
        refresh_emergency_recovery_state: Any
        refresh_pi_storage_from_pi: Any
        refresh_settings_unsaved_baseline: Any
        remember_session_credentials_after_save: Any
        remove_admin_from_ui: Any
        render_camera_frame_from_worker: Any
        render_dashboard_users: Any
        render_face_users: Any
        require_admin_for_tab: Any
        resize: Any
        restore_main_window_for_attention: Any
        resume_camera_after_modal: Any
        resume_locking_after_pi_reconnect: Any
        retry_pi_connection_until_restored: Any
        return_to_settings_from_pi_disconnect: Any
        ring: Any
        rollback_preview_synced_pi_settings_after_discard: Any
        runtime_lock_service: Any
        sas_check_received_btn: Any
        sas_client_id: Any
        sas_client_name: Any
        sas_oneconnect_force_takeover_active: Any
        sas_oneconnect_heartbeat_timer: Any
        sas_oneconnect_session: Any
        sas_received_badge_label: Any
        sas_received_poll_initialized: Any
        sas_received_popup_visible: Any
        sas_received_seen_files: Any
        sas_received_timer: Any
        sas_received_tray_icon: Any
        save_settings_from_ui: Any
        security_option_buttons: Any
        security_options_card: Any
        send_sas_oneconnect_heartbeat: Any
        server_configured: Any
        server_credentials_card: Any
        server_path: Any
        setCentralWidget: Any
        setEnabled: Any
        setMinimumSize: Any
        setWindowFlags: Any
        setWindowIcon: Any
        setWindowState: Any
        setWindowTitle: Any
        set_auto_capture_sync_status: Any
        set_camera_rotation_from_ui: Any
        set_camera_state_badge: Any
        set_capture_button_manual_mode: Any
        set_face_capture_in_progress: Any
        set_face_controls_connection_enabled: Any
        set_face_controls_training_busy: Any
        set_face_detected: Any
        set_footer_mode: Any
        set_ntid_input_error: Any
        set_pi_status_label: Any
        set_pi_storage_unavailable: Any
        set_save_connect_busy: Any
        set_selected_pi_host_runtime: Any
        set_sftp_status: Any
        set_transfer_status: Any
        settings_button: Any
        settings_card_base: Any
        settings_input: Any
        settings_label: Any
        settings_ntid_input: Any
        settings_page: Any
        settings_password_input: Any
        settings_save_connect_btn: Any
        settings_server_path_input: Any
        should_auto_show_pi_disconnect_popup: Any
        should_suppress_auto_pi_disconnect_popup: Any
        should_suspend_inactivity_lock: Any
        show: Any
        showMaximized: Any
        showMinimized: Any
        show_authorized_users_dialog: Any
        show_camera_stopped_prompt: Any
        show_capture_complete_popup: Any
        show_connection_dialog: Any
        show_delete_complete_popup: Any
        show_face_tab_pi_disconnect_popup: Any
        show_guidelines_dialog: Any
        show_missing_credentials_setup_popup_if_needed: Any
        show_oneconnect_conflict_dialog: Any
        show_oneconnect_conflict_prompt: Any
        show_pi_disconnect_alert_if_needed: Any
        show_pi_disconnected_popup: Any
        show_settings_message: Any
        show_sftp_download_success: Any
        show_system_locked_notification: Any
        show_transfer_button_failed: Any
        show_transfer_button_success: Any
        show_unsaved_settings_dialog: Any
        stack: Any
        start_camera_preview: Any
        start_pi_disconnect_retry_loop: Any
        start_timers: Any
        start_transfer_button_loading: Any
        start_websocket_lock_session: Any
        startup_background_mode_check: Any
        status_card: Any
        status_card_widget: Any
        status_lock_icon: Any
        status_pill: Any
        status_title: Any
        status_watermark: Any
        stop_camera_preview: Any
        stop_export_loading_timer: Any
        stop_recognition_websocket: Any
        stop_transfer_button_loading: Any
        suspend_locking_for_pi_disconnect: Any
        switch_top_tab: Any
        sync_auto_capture_setting_now: Any
        sync_settings_to_pi_async: Any
        system_locked_notification: Any
        system_log_body: Any
        system_log_card: Any
        system_log_label: Any
        system_log_scroll: Any
        tab_indicator: Any
        tab_indicator_anim: Any
        time_label: Any
        time_left: Any
        time_section: Any
        timeout_inputs: Any
        timer_circle_front: Any
        toggle_lock_state: Any
        toggle_login_password: Any
        toggle_pi_connection_from_settings: Any
        top_nav_buttons: Any
        total_seconds: Any
        training_dialog: Any
        transfer_input_row: Any
        ui_bridge: Any
        ui_scale: Any
        update_account_button: Any
        update_account_ui: Any
        update_camera_rotation_ui: Any
        update_countdown: Any
        update_dashboard_card_sizes: Any
        update_face_card_sizes: Any
        update_face_detected_label: Any
        update_footer_info: Any
        update_pi_connect_ui_state: Any
        update_pi_storage_ui: Any
        update_time: Any
        update_training_dialog_progress_from_status: Any
        user_row: Any
        users_card: Any
        validate_primary_ntid: Any
        validate_server_path_for_settings: Any
        validate_settings_credentials_strict: Any
        validate_transfer_inputs: Any
        verify_pi_status_after_action: Any
        vertical_line: Any
        wait_until_pi_camera_stopped: Any
        wait_until_pi_capture_complete: Any
        wait_until_pi_recognition_running: Any
        wait_until_pi_training_finished: Any
        websocket_client_service: Any
        websocket_lock_session_id: Any
        width: Any
        winId: Any
        windowFlags: Any
        windowState: Any
        write_sas_log: Any

        def __getattr__(self, name: str) -> Any: ...
        def __setattr__(self, name: str, value: Any) -> None: ...

else:
    class DashboardMixinBase:
        pass
